-- 코드를 입력하세요

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) SCORE
-- I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),3) SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID
AND I.ADDRESS IN (SELECT ADDRESS FROM REST_INFO WHERE SUBSTR(ADDRESS,1,2)='서울')
GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
-- , I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,R.REVIEW_SCORE
ORDER BY SCORE DESC, I.FAVORITES DESC;

