SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME='Python')
OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='C#')
ORDER BY ID;
# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS d
# WHERE EXISTS(SELECT 1
#              FROM SKILLCODES s
#             WHERE s.NAME IN ('Python', 'C#') AND
#              d.SKILL_CODE & s.CODE = s.CODE )
# ORDER BY ID